#####################
# app-saludo ----------------------------------------------
#####################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-saludo-taint-deployment
  namespace: intro-k8s
  labels:
    app: app-saludo
    maintainer: matiops
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-saludo
  template:
    metadata:
      labels:
        app: app-saludo
    spec:
      containers:
      - name: app-saludo
        image: matiops/intro-k8s:app-saludo
        ports:
        - containerPort: 8000
      nodeSelector: # <- Es una especificación del POD
        hardware: gpu
      #tolerations:
      #- key: "dedicated"
      #  operator: "Equal"
      #  value: "gpu"
      #  effect: "NoExecute" # ¿Se puede poner "NoSchedule"?
---
apiVersion: v1
kind: Service
metadata:
  name: app-saludo-taint-service
  namespace: intro-k8s
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8000
  selector:
    app: app-saludo
