---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    appName: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      appName: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        appName: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
        resources:
          requests:
            memory: {{ .Values.app.memory.request }}
            cpu: {{ .Values.app.cpu.request }}
          limits:
            memory: {{ .Values.app.memory.limit }}
            cpu: {{ .Values.app.cpu.limit }}